### ISSUE TITLE
Add is/== difference

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#119]
Many people think that `is` works like `eq` in Java rather than being on identity.

Probably because they see it used like

`if foo is None then`

on primitive types that are singletons.

whereas

`if foo is String then`

will never be true because it instantiates a new String and compares the identity of it to the identity of `foo`. In most instances people want `eq` like if foo == some_string then`

its also possible they are attempting to check the type (this is common as well) and need to use a match statement:

```pony
match foo
| let s: String => ...
else
 ...
end
```

**Comment by MrMormon** [comment]
Maybe [infix ops](https://github.com/ponylang/pony-tutorial/blob/master/expressions/infix-ops.md)? That's where `and`, `or`, and `==`/`eq()` are introduced, and `is` is missing.
