### ISSUE TITLE
Wrong markdown coding re. "Case functions"

### ISSUE THREAD

**Issue by jkleiser** [ponylang/pony-tutorial#143]
On http://tutorial.ponylang.org/expressions/infix-ops.html it seems that `(Case functions)[http://tutorial.ponylang.org/pattern-matching/case-functions.html]` should be changed into `[Case functions](http://tutorial.ponylang.org/pattern-matching/case-functions.html)`.

**Comment by SeanTAllen** [comment]
Can you PR that @jkleiser ?

**Comment by jkleiser** [comment]
Hi @SeanTAllen. As you may have seen, I have just made that PR.

**Comment by jemc** [comment]
Resolved by #144.
