### ISSUE TITLE
Remove homebrew warning

### ISSUE THREAD

**Issue by danielcompton** [ponylang/pony-tutorial#151]
From [installation instructions](https://github.com/Homebrew/homebrew-core/blob/6d37af4a1e501edcad03c01e785c653b0243d544/Formula/ponyc.rb) in getting started

> The homebrew version is currently woefully out of date. We are transitioning to a new release system that will keep homebrew up to date. For now, please build from source.

but looking at the [formula](https://github.com/Homebrew/homebrew-core/blob/6d37af4a1e501edcad03c01e785c653b0243d544/Formula/ponyc.rb), it seems to be up to date now?

Can this warning be removed?

**Comment by jemc** [comment]
Indeed it can - thanks for noticing.

Our release mechanisms are back on track and we will be shipping releases on a regular schedule from now on, including to homebrew.

**Comment by SeanTAllen** [comment]
@danielcompton these instructions are out of date. we currently have instructions in two locations. by the end of this week, it will only be 1 location and everything will be up to date.

Maintaining instructions in two locations has not been enjoyable.

**Comment by SeanTAllen** [comment]
This is fixed. Installation instructions now point to the GH repo README which is up to date.
