### ISSUE TITLE
Symbol lookup cheatsheet rendered incorrectly on tutorial.ponylang.org

### ISSUE THREAD

**Issue by avsej** [ponylang/pony-tutorial#159]
It seems like gitbook handles `|` (pipe symbol) incorrectly (or different at least).
https://tutorial.ponylang.org/appendices/symbol-lookup-cheatsheet.html

![image](https://cloud.githubusercontent.com/assets/7280/19211767/2589feda-8d4d-11e6-839f-58ac736440f4.png)

**Comment by SeanTAllen** [comment]
Yes. This is a known issue.

**Comment by mfelsche** [comment]
This renders nicely in all browsers i've tried. Considering this as resolved.
