### ISSUE TITLE
Add subsection to explain methods capabilities constrained by viewpoint on receiver

### ISSUE THREAD

**Issue by obadz** [ponylang/pony-tutorial#173]
i.e.:

```pony
fun box blah(…)
```

`box` is implicit, `blah` cannot modify fields of the receiver.

```pony
fun ref set(…)
```

`ref` here means `set` can modify fields.

**Comment by rhagenson** [comment]
I think this is covered by #449 (and other updates since this issue was opened) so I am closing.
