### ISSUE TITLE
Broken Syntax Coloring

### ISSUE THREAD

**Issue by civ** [ponylang/pony-tutorial#180]
On this page some of the coloring is broken https://tutorial.ponylang.org/types/type-aliases.html#complex-types 
The first box in  Complex Types is missing some colors and right before Complex Types in the line
`for colour in ColourList().values() do
`
for and values are not colored, either.

Only the HTML is broken, on github the syntax is colored just right:
https://github.com/ponylang/pony-tutorial/blob/master/types/type-aliases.md#complex-types

You can see the difference in the attachments. 
I don't know how to fix that, so yeah :) 

github:
![github](https://cloud.githubusercontent.com/assets/7314680/24189868/effa74e0-0ee6-11e7-93a2-9e8e1e7c6699.PNG)
tutorial.ponylang:
![tutorial ponylang](https://cloud.githubusercontent.com/assets/7314680/24189869/effce5ae-0ee6-11e7-8a74-3ffa7e800f04.PNG)

**Comment by SeanTAllen** [comment]
This would be a highlight.js bug and would need to be fixed against it.

**Comment by SeanTAllen** [comment]
Closing as this is a highlight.js bug.
