### ISSUE TITLE
Flesh out examples in "Types" and "Expressions" sections

### ISSUE THREAD

**Issue by non-Jedi** [ponylang/pony-tutorial#200]
It would have helped immensely in quickly learning the language if I could have copied code examples from the tutorial add compiled them directly in the first few sections. This issue is basically caused by the fact that instantiation isn't covered at all until the "Methods" subsection of "Expressions". After coming to that section, I found myself rereading the "Types" section so that I could actually practice on the given examples.

This seems like it's as simple as adding an `actor Main` to most examples and printing a few lines.

This issue may also be largely resolved by a change in organization of the tutorial. It might make more sense to have the "Expressions" section before the "Types" section.

(I'm trying to note down all the problems I run into as I *slowly* work my way through the tutorial. The hope is that I'll come back and PR to resolve these issues once I better understand Pony.)

**Comment by SeanTAllen** [comment]
This has been added @non-Jedi!
