### ISSUE TITLE
Make clear what the value of a loop is

### ISSUE THREAD

**Issue by non-Jedi** [ponylang/pony-tutorial#214]
From https://tutorial.ponylang.org/expressions/control-structures.html:
>In Pony there are no statements there are only expressions, everything hands back a value. Your if statement hands you back a value. Your for loop (which we'll get to a bit later) hands you back a value.

But for the life of me, I can't figure out what value a for loop hands back.

**Comment by jemc** [comment]
It's a totally valid question, and you're right that we should be covering it in the tutorial.

For the record, the value of a loop expression is the value of the final expression in the loop body's final iteration, or the value of the final expression in the `else` body if the loop had zero iterations. If there is no `else` clause, the implied `else` value is `None`.
