### ISSUE TITLE
Incorrect description of the difference between static and dynamic typing

### ISSUE THREAD

**Issue by markoutso** [ponylang/pony-tutorial#259]
https://tutorial.ponylang.org/types/at-a-glance.html

In the paragraph static vs dynamic the author reports that

> With a dynamically typed language, a variable can point to objects of different types at different times. This is flexible, because if you have a variable x, you can assign an integer to it, then assign a string to it, and your compiler or interpreter doesn't complain.

I think that this paragraph describes better the distinction of strong vs weak typing instead of static vs dynamic.

A correct definition of the distinction would be something like:

>  In a dynamically typed language the type of a variable is checked during runtime whereas in a statically typed language the compiler checks the type of a variable during compilation.

**Comment by willhbr** [comment]
I think the current description is correct. The key behaviour that makes a language weakly typed is the implicit conversion of the type of a variable depending on how it is used. Being able to change the type of a variable by assigning a different value does not make it weakly typed.

In a strongly typed language like Python you can assign different types to a variable, but if you do an operation to it that isn't available on that type it will not be converted. Whereas in Javascript or PHP - dynamically and weakly typed - certain operations will change the type of a variable depending on its value, the typical example being maths operators.

The way I read your definition makes it seem like a dynamically typed language will forbid changing the type of a variable, but only at runtime - which is not how most dynamic languages work. Although this could just be me misreading.
