### ISSUE TITLE
The FFI section should be revised to include more details about the C/Pony API and ABI compatibility and good practices

### ISSUE THREAD

**Issue by Praetonus** [ponylang/pony-tutorial#263]
This is a list of things that either are imprecise or are bothering me in the current FFI section of the tutorial. Discussion is open on whether the good practices I'm going to recommend really are good practices.

1. Clarify the C/Pony type mapping. In particular, the tutorial should make it clear that Pony classes and structs are reference types equivalent to C pointer-to-structs and that only Pony structs can be used to represent non-opaque C structs.
2. State that passing things by value in the FFI isn't possible at the moment, but that it is something we intend to support in the future.
3. Recommend `Pointer[None]` for `void*` instead of `Pointer[U8]` since `Pointer[None]` basically has `void*` semantics in FFI parameters, where it is a supertype of every ABI-compatible type.
4. Detail why pointers to primitives are used for opaque types instead of `Pointer[None]`. This doesn't change anything at the ABI level but provides some amount of type safety. In addition, state that the associated primitives shouldn't be used anywhere except as type parameters to `Pointer`. This avoids any misuse of the FFI.
5. Clarify the usage of `MaybePointer` and what it means for the API and ABI. It is only useful as a return type or an output parameter type (possibly nested in a struct in both cases), where receiving a null value on the Pony side is a possibility. It is unnecessary as an input parameter type.

**Comment by jemc** [comment]
Can you clarify this one?

> the associated primitives shouldn't be used anywhere

**Comment by Praetonus** [comment]
@jemc We should advise against things like this:

```pony
primitive Foo

@foo[Foo]()
```

Since an FFI function can return anything, if you do that there's a high chance that the `Foo` you got back isn't the true `Foo` singleton value, and that's bad.
