### ISSUE TITLE
Wombat Delegate Example

### ISSUE THREAD

**Issue by graymalkin** [ponylang/pony-tutorial#28]
```pony
trait Wombat
  fun box battle_call() : String val => 
    "Huzzah!"

class SimpleWombat is Wombat

actor Main is Wombat
  let w : SimpleWombat delegate Wombat = SimpleWombat

  new create(env : Env) =>
    env.out.print("Battle cry: " + battle_call())
```

Is this the best example of delegation in pony? Would jumping straight in with the type mixing be a better explanation? (Please excuse my being a bit of a tenderfoot with ponylang)

**Comment by darach** [comment]
Yes, diving straight in with type mixing might be better Feel free to fork and contribute a PR!

**Comment by jkleiser** [comment]
I just found another Delegate example here, almost at the bottom:
http://tutorial.ponylang.org/examples/examples/

**Comment by SeanTAllen** [comment]
Delegate documentation removed for now from the tutorial.
