### ISSUE TITLE
Structs section for Chapter 2

### ISSUE THREAD

**Issue by michaelsbradleyjr** [ponylang/pony-tutorial#282]
`struct` is introduced in the [Calling C from Pony](https://tutorial.ponylang.org/c-ffi/calling-c.html) section of Chapter 10. I can see how that makes sense.

However, as a newcomer to Pony, I jumped ahead in the book at one point (taking a break from reading about Capabilities), and encountered `struct` in the [Callbacks](https://tutorial.ponylang.org/c-ffi/callbacks.html) section. I didn't recognize the keyword and instinctively went back to Chapter 2 as I thought it must have been in a "Types" section that I didn't read too closely.

Perhaps it would make sense to include a "Structs" section in Chapter 2 that doesn't say too much, just introducing the syntax, and noting that more will be explained in Chapter 10. Also, I think the intro-explanation of `struct` in Chapter 10 could be augmented by another sentence or two (it just feels too brief, but other than that I don't have suggestions on what should be added).

**Comment by SeanTAllen** [comment]
@michaelsbradleyjr I've opened a PR to address this. #364.
