### ISSUE TITLE
Tutorial lacks mention of syntax for constructor style: let x: T = x.create()

### ISSUE THREAD

**Issue by slfritchie** [ponylang/pony-tutorial#284]
Today in the #ponylang IRC channel, `brainproxy` asked a question about this syntax in the Pony Patterns doc, in the "Access" section.

    let _data: collections.Map[String, I64] = _data.create()

Neither `brainproxy` nor I can find an example or explanation in the Pony tutorial that mentions this style use.  By my own skim, I found one almost-but-not-quite in the "Methods" section of the tutorial, the "Calling" subsection:

    var b: Foo = a.from_int(3)

**Comment by rhagenson** [comment]
As far as I can tell this syntax has been covered in the tutorial for some time now.

https://github.com/ponylang/pony-tutorial/blob/7e880412a2250ddc8c6611066ed613f3ae760766/content/expressions/methods.md#L86-L89

**Comment by EpicEric** [comment]
@rhagenson, that's not the same syntax mentioned in the original post. Instead, it's when you use the same variable name you are declaring to call `create()`. For example:

```pony
class Bar
  fun f() =>
    var a: Foo = Foo.create()
    var b: Foo = Foo.from_int(3)
    var c: Foo = c.create() // This one
```

**Comment by rhagenson** [comment]
Got it. I see the distinction now. I can add an example of that now that I understand where the confusion is. Thank you for clarifying!
