### ISSUE TITLE
Red code-words get broken in Chrome and Safari

### ISSUE THREAD

**Issue by jkleiser** [ponylang/pony-tutorial#29]
If you take a look at e.g. http://tutorial.ponylang.org/capabilities/recovering-capabilities/ in Chrome (Mac or Windows), you will probably see that some red code-words like "String", "box" and "recover" get broken at the end of the line. (It doesn't happen in Firefox or IE.) In Chrome I have fixed it, using the Stylebot extension, by entering this:
```
p code {
  word-wrap: normal;
}
```
I also think the code samples use too tiny font, so I've entered this as well:
```
code {
  font-size: 90%;
}
```

**Comment by SeanTAllen** [comment]
Move off of Mkdocs. Should be an issue with new hosting.
