### ISSUE TITLE
No rationale provided for `where` syntax

### ISSUE THREAD

**Issue by rodrigob** [ponylang/pony-tutorial#291]
Section https://github.com/ponylang/pony-tutorial/blob/59b6d9ac9a5f7cd7668c332d5686876ab0d51315/expressions/methods.md#named-arguments

introduces the `where` keyword.
For `elseif` a clear rationale was provided, contrasting to C syntax.

For python programmers it is unclear what the `where` keyword provides. Adding some rationale for the more verbose syntax would be great.

**Comment by SeanTAllen** [comment]
I'm not sure why is unclear "for python programmers" regarding `where`. Can you elaborate?
