### ISSUE TITLE
Run in playground gives 401

### ISSUE THREAD

**Issue by tirkarthi** [ponylang/pony-tutorial#295]
When I try to click on the run in playground in [this](https://tutorial.ponylang.org/getting-started/how-it-works.html) page then it makes an API call to https://api.github.com/gists which gives the below response with 401 status code. I have logged into GitHub but the issue still persists. 

Error message from GitHub's API : 

```
{
  "message": "Requires authentication",
  "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist"
}
```

Thanks

**Comment by plietar** [comment]
Thanks @tirkarthi for letting us know.
https://github.com/ponylang/gitbook-plugin-copy-code-button-ponylang/pull/1 should do the trick

**Comment by plietar** [comment]
@seantallen do you know what the process is to get the fix on the tutorial?

**Comment by SeanTAllen** [comment]
@plietar maybe

**Comment by SeanTAllen** [comment]
working on it

**Comment by SeanTAllen** [comment]
@plietar need @jemc to do a bit of it.

**Comment by SeanTAllen** [comment]
Fixed
