### ISSUE TITLE
The helloworld program fails to compile/link on Debian 9.5 stretch (without --pic)

### ISSUE THREAD

**Issue by karmakaze** [ponylang/pony-tutorial#301]
[edit: later in this thread, we discover problem is with using the `deb` source listed for Debian systems and a similar issue arises when compiling without `--pic` on a **debian** system. title updated]

On a default install of Ubuntu 18.04 and following the Pony installation instructions using .deb we end up with gcc and without clang. Running `ponyc` in the `helloworld` directory results in a link error:
```
Warning: environment variable $CC undefined, using gcc as the linker
Error:
unable to link: gcc -o ./test -O3 -march=x86-64 -mcx16 -latomic  -fuse-ld=gold ./test.o -L"/usr/lib/pony/0.23.0-1/bin/" -Wl,-rpath,"/usr/lib/pony/0.23.0-1/bin/" -L"/usr/lib/pony/0.23.0-1/bin/../lib" -Wl,-rpath,"/usr/lib/pony/0.23.0-1/bin/../lib" -L"/usr/lib/pony/0.23.0-1/bin/../packages" -Wl,-rpath,"/usr/lib/pony/0.23.0-1/bin/../packages" -L"/usr/local/lib" -Wl,-rpath,"/usr/local/lib" -Wl,--start-group -Wl,--end-group  -lpthread  -lponyrt -ldl -lm 
```

Until the default installation 'just works' I think _we should add a small note in the tutorial_ so the first thing a Linux user hits isn't a mysterious error message. We can either suggest using `ponyc --pic` or `export CC=clang` along with `sudo apt install clang`. The former seems like the quicker way to continue the tutorial and the latter (if set persistently) less typing. I don't know the difference between using `gcc` vs `clang` to make a recommendation.

**Comment by jemc** [comment]
Rather than changing the tutorial, I think we need to fix the installation. The `deb` package probably needs to have its ponyc be compiled with `default_pic=true`,

**Comment by dipinhora** [comment]
@karmakaze I'm unable to reproduce your issue using Docker. Please provide steps to reproduce.

The PPA build of ponyc already has `default_pic=true` so you should not be running into a PIC related linking issue.

I ran the following in Docker (`sudo docker run --rm -it ubuntu:18.04`) to install ponyc and then compile helloworld without any errors:

```
apt-get update
apt-get install software-properties-common
add-apt-repository ppa:ponylang/ponylang
apt-get update
apt-get install ponyc
mkdir /tmp/hw
echo 'actor Main' >> /tmp/hw/main.pony
echo '  new create(env: Env) =>' >> /tmp/hw/main.pony
echo '    env.out.print("Hello, world.")' >> /tmp/hw/main.pony
cd /tmp/hw
ponyc
./hw
```

Just in case the issue was not occurring due to docker running as `root` by default, I created the following `Dockerfile`:

```
FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install software-properties-common -y \
    && add-apt-repository ppa:ponylang/ponylang -y \
    && apt-get update \
    && apt-get install ponyc -y
```

Built it using:

```
sudo docker build . -t ubuntu-18.04-ponyc
```

Then ran it using:

```
sudo docker run --rm -it -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro --user 1000:1000 ubuntu-18.04-ponyc:latest
```

In the running docker container, I ran the following without any errors to build and run helloworld:

```
mkdir /tmp/hw
echo 'actor Main' >> /tmp/hw/main.pony
echo '  new create(env: Env) =>' >> /tmp/hw/main.pony
echo '    env.out.print("Hello, world.")' >> /tmp/hw/main.pony
cd /tmp/hw
ponyc
./hw
```

**Comment by karmakaze** [comment]
I've checked on two Ubuntu 18.04 machines, and running `ponyc --version` on each shows:
```
0.24.0 [release]
compiled with: llvm 3.9.1 -- cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Defaults: pic=true ssl=openssl_1.1.0
```
This is good as expected.

The other is showing:
```
0.23.0-59eac3b [release]
compiled with: llvm 3.9.1 -- gcc (Ubuntu 6.4.0-17ubuntu1~14.04) 6.4.0 20180424
Defaults: pic=false ssl=openssl_0.9.0
```
It turns out this one wasn't installed from `ppa:ponylang/ponylang` but rather `deb https://dl.bintray.com/pony-language/ponyc-debian pony-language main` which is intended for Debian systems. So I would say this one is a misconfiguration error on my part.

Following-up on a Debian 9.5 (stretch) system, `ponyc --version` shows:
```
0.24.0-79af8a0 [release]
compiled with: llvm 3.9.1 -- gcc (Ubuntu 6.4.0-17ubuntu1~14.04) 6.4.0 20180424
Defaults: pic=false ssl=openssl_0.9.0
```
and running `ponyc` in a directory containing the sample `hello world` source: results in error messages that say `recompile with --fPIC`. This was with `gcc` installed. Finally running `ponyc --pic` on the Debian 9.5 system worked as expected.

So in the end, the issue is with following the tutorial directions on Debian (9.5 and perhaps others) with gcc.

**Comment by SeanTAllen** [comment]
I think this can be closed. Any objections?
