### ISSUE TITLE
make code sample in "division by zero" section valid Pony

### ISSUE THREAD

**Issue by aturley** [ponylang/pony-tutorial#309]
The following code snipped appears in the "Division by Zero" section:

```pony
let x = 1 / 0
```

This isn't valid Pony because there's no type information. We should figure out a way to make this example into something that (when included as part of a program) will compile.

Either of these two options works for me:

```ponyc
let a: I32 = 1
let b: I32 = 0
let x = a / b
```

or

```ponyc
let x = I32(1) / I32(0)
```

Any other thoughts?

**Comment by mfelsche** [comment]
And the current example is catched by the lexer, which does not allow division by literal `0`.

I would prefer the second example.

Thanks for taking care of this.
