### ISSUE TITLE
One typo, and color vs. colour

### ISSUE THREAD

**Issue by jkleiser** [ponylang/pony-tutorial#31]
In http://tutorial.ponylang.org/types/type-aliases/#complex-types I find this extra "the":
"you might also want to iterate over the the enum …"
You could also write "You" instead of "you" here.
The tutorial uses both "colour" and "color". You should choose one. I prefer using "color" in computer tech literature.

**Comment by andymcn** [comment]
You're entirely right, there are quite a few typos on that page, particularly in the example code. Please feel free to fix it up and submit a patch!

As for the question of British vs American spelling, we really should come up with a policy and stick to it. The bulk of the tutorial was written by a Brit, a British-naturalised American and a German, so we tend to use British spellings, but maybe we shouldn't.

**Comment by jkleiser** [comment]
In my local clone I have done "git checkout -b typo_and_color_to_colour", made the changes (incl. Colors -> Colours), and done "git add ..." on two .md files. Now I try "git push origin typo_and_color_to_colour", but I get this:
```
remote: Permission to CausalityLtd/pony-tutorial.git denied to jkleiser.
fatal: unable to access 'https://jkleiser@github.com/CausalityLtd/pony-tutorial.git/': The requested URL returned error: 403
```
Do you know what I'm doing wrong?

**Comment by sblessing** [comment]
Have you forked the repo and did the changes to your local repo?

**Comment by jkleiser** [comment]
No, I have not forked this time.

**Comment by sblessing** [comment]
which you need to, since you probably do not have write/owner rights on the original repo

**Comment by jkleiser** [comment]
OK. Thanks, I'll do that.

**Comment by jkleiser** [comment]
Could you please help me with this one:
Is there an easy way to update my fork so that it matches the current CausalityLtd/pony-tutorial?
If not, how do I delete my fork, so I can make a new one from the current CausalityLtd/pony-tutorial?
I have done it once before, but the web UI has changed. ;-)

**Comment by andymcn** [comment]
Assuming you're using git on the command line, you can do:
```
git fetch upstream
```
which will get updates from CausalityLtd/pony-tutorial into your local workspace. You can then commit them to your repo as normal.

I have no idea how to delete a github fork anymore, they've taken away the button!
