### ISSUE TITLE
Make unary vs binary operator precedence more clear.

### ISSUE THREAD

**Issue by jemc** [ponylang/pony-tutorial#324]
We want to make the tutorial clearly call out how unary operators bind more closely than binary operators, and that unary vs binary operator precedence is "a thing" in Pony, despite our stance on not allowing different binary operators to have different levels of precedence.

The goal is to make clear and explicit the behaviour that led to the filing of this ticket: https://github.com/ponylang/ponyc/issues/1973

**Comment by rhagenson** [comment]
There is a brief statement to this effect in the Operators->Precedence section:

https://github.com/ponylang/pony-tutorial/blob/7e880412a2250ddc8c6611066ed613f3ae760766/content/expressions/ops.md#L140-L142

I could reasonably add a repetition of the concept using a unary operator on the arithmetic that follows the above mention. Something akin to:

```
1 + (2 * -3)
```

To show that it make sense for the unary `-` to bind more closely than the binary `*`.

**Comment by SeanTAllen** [comment]
@rhagenson we discussed at sync and think your idea is a good one.

**Comment by rhagenson** [comment]
@SeanTAllen I will get the addition made and a PR submitted.
