### ISSUE TITLE
Keyword listing is missing `isnt`

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#336]
https://tutorial.ponylang.io/appendices/keywords.html doesn't have `isnt`. 

😢 

it should then we can be

😄

**Comment by dangoldin** [comment]
So this is the counterpart to "is"

For is the definition is:

```
is | (1) used in nominal subtyping
-- | --
  | (2) in type aliasing
```

I'm thinking here the documentation can be the same with a note that it's the opposite of is?
