### ISSUE TITLE
New to add search to new site

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#339]
Thoughts on best approach @mfelsche ?

**Comment by mfelsche** [comment]
I have to look into the general setup, but as a rough sketch: Generate the search index from the markdown files into a json file and ship it with the generated html, so the search box can pick it up and doesnt need to build the index as the tutorial currently has to. All this assumes lunr.js is used. But maybe there is already a good plugin for hugo to set this up.

Gimme some time to investigate as this is all new ground to me.

**Comment by SeanTAllen** [comment]
@mfelsche if we go the lunr.js route then: https://halfelf.org/2017/hugos-lunr-search/ is a bit of insight. plus there are hugo templates with lunr integrated that we could check out and see how they do it.

another option algolia. thoughts on which we should prefer?

**Comment by SeanTAllen** [comment]
Merged to master. Thanks @mfelsche!
