### ISSUE TITLE
Broken links to .md instead of .html in the "Divide by Zero" HTML page

### ISSUE THREAD

**Issue by peroksid** [ponylang/pony-tutorial#342]
At https://tutorial.ponylang.io/gotchas/divide-by-zero.html links to "Partial division", "Unsafe Division" and "Partial or Checked Division" lead to https://tutorial.ponylang.io/expressions/arithmetic.md (with some anchors). The links are broken. HTML version ust link to https://tutorial.ponylang.io/expressions/arithmetic.html.

**Comment by SeanTAllen** [comment]
Thanks for reporting @peroksid

**Comment by peroksid** [comment]
Hi Sean, there are a few more .md links, look at https://github.com/peroksid/pony-tutorial/commit/8aaf1df15d8398cd938128188f94bbae84254d52.
