### ISSUE TITLE
Object capabilities section of tutorial is anemic

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#362]
Has 

- no examples of code that use capabilities (file example, tcp example would both be good)
- has no examples of how those capabilities work under the hood
- doesn't really explain what "ambient authority" is
- doesn't show how to create your own capabilities for a library

**Comment by EpicEric** [comment]
[Here's some helpful discussion](https://ponylang.zulipchat.com/#narrow/stream/189985-beginner-help/topic/AmbientAuth.20(and.20other.20auths.3F)) from Zulip that can be incorporated into this issue.

**Comment by rhagenson** [comment]
Closed by #472
