### ISSUE TITLE
Clarify "Aliased substitution"

### ISSUE THREAD

**Issue by schnittchen** [ponylang/pony-tutorial#379]
Sorry if this is more a question... I will try to provide improvements once this is clear to me.

The "rules" of "Aliased substitution" here (https://tutorial.ponylang.io/reference-capabilities/capability-subtyping.html) are hard consequences of

* the "whatever we can safely alias this thing as" "definition" of alias types as found here (https://tutorial.ponylang.io/reference-capabilities/aliasing.html)
* the individual aliasing transitions as described under "Aliasing and deny guarantees" (https://tutorial.ponylang.io/reference-capabilities/aliasing.html)

I understand that aliased substitution is necessary to make aliases in generic types possible. Once a type parameter in a generic type is resolved to a concrete type, is there (apart from compiler technicalities, fex. the ability to provide good error messages) any difference to a simple substitution à la "`iso!` is substituted with `tag`"?

If that is the case, I would suggest reducing the "Aliased substitution" section (the exact rules are already found elsewhere) and possibly moving some stuff around.

**Comment by jemc** [comment]
If I understand you correctly, I think you have the correct concepts, but am curious what specific changes you want to propose to improve the wording. We're open to anything that improves clarity.

**Comment by jemc** [comment]
(To be clear, my understanding is that you're saying it's confusing to say that `iso!` is a subtype of `tag` when really the compiler is just replacing it with `tag`?)

**Comment by jasoncarr0** [comment]
Closing via #449
