### ISSUE TITLE
Type parameter type defaults seem to be missing

### ISSUE THREAD

**Issue by schnittchen** [ponylang/pony-tutorial#385]
I'm referring to things like the `[B: ... ref = Array[A!]]` part here https://stdlib.ponylang.io/src/itertools/iter/#L259.

I could not find this in the tutorial.

Please feel free to correct me on the terminology.

**Comment by rhagenson** [comment]
As this issue sits at the intersection of Pony generics it is a little more complicated, but not unreasonable for a first issue. Anyone wishing to tackle this issue, feel free to reach out to me. First we will need to decide where in the Tutorial is best for this and a minimal example to show type parameterization with a default.

**Comment by EpicEric** [comment]
Closed in #467.
