### ISSUE TITLE
include information about constructors with no arguments

### ISSUE THREAD

**Issue by aturley** [ponylang/pony-tutorial#401]
If a constructor doesn't take any arguments then the constructor is invoked without using parenthesis. If no constructor is supplied then this is how you create an object. This can be confusing to users who are reading the "Constructors" section of the tutorial because no mention is made of this behavior, so if a user creates their own class with no constructor they will probably try to create an instance using `Foo()`, and they will get an error message saying that there is no `apply()` method.

You can see this happening in [this video of someone trying to learn Pony from the tutorial](https://www.youtube.com/watch?v=ptrnhrpaLO4&t=18m45s).

**Comment by EpicEric** [comment]
It is explained in the [Sugar subsection](https://tutorial.ponylang.io/expressions/sugar.html#create).

**Comment by aturley** [comment]
It is explained in the Sugar subsection, but it I think it could be useful to explain it in the context where users are likely to encounter it first.

If I recall correctly, the intent was that users would be able to read the tutorial linearly and learn Pony (I'm sure I'm missing some nuance here and someone will be happy to provide that). We have one instance of someone being confused by this, I remember being confused by this when I was first learning Pony, and I wouldn't be surprised if others have been confused by this.

**Comment by SeanTAllen** [comment]
Closed by #402
