### ISSUE TITLE
Default refcaps on classes/objects

### ISSUE THREAD

**Issue by RHagenson** [ponylang/pony-tutorial#404]
A recent conversation in the Zulip between Nate Watts and Eric (@EpicEric) revealed confusing wording in: [Reference Capabilities -> Reference Capabilities -> Type Qualifiers](https://tutorial.ponylang.io/reference-capabilities/reference-capabilities.html#type-qualifiers).

Current wording is:

> In Pony, every use of a type has a reference capability. These capabilities apply to variables, rather than to the type as a whole. In other words, when you define a class Wombat, you don’t pick a reference capability for it. Instead, Wombat variables each have their own reference capability.

and suggests to the new learner that when defining a class in Pony you do not pick a refcap for that class. When in reality, when defining the class you define the default refcap (with a further default of `ref` when not defined), which can be overridden for each instance of that class.

Eric stated the following to clarify meaning:

>  When you define a class, you specify a default capability for the class. When you leave it empty, it's implicitly `ref`. But some others, such as `class val String`, explicitly choose another default capability. But objects can have any capability available to them, through constructors + recover blocks or subtyping.

> A better text for the first part would be: "In other words, when you define a class Wombat, you don’t pick a reference capability for all instances of the class. Instead, Wombat variables each have their own reference capability."

I think clarification of this default versus overriding of refcaps on user-defined classes is in order. If it was unclear to one person, it is likely to be unclear to more. I also suspect there is more than one place this clarification can be emphasized to help cement the concept through repetition in the tutorial.

**Comment by SeanTAllen** [comment]
@EpicEric you seem to have a good feel for this, would you be open to doing a PR for this?
