### ISSUE TITLE
Exercism: Add a Pony language track

### ISSUE THREAD

**Issue by nazarsh** [ponylang/pony-tutorial#420]
As a beginner
I would love to have a Pony language track on [Exercism](https://exercism.io/)
So that I can practice Pony as I am learning it from the guide

**Comment by SeanTAllen** [comment]
One already exists.

https://exercism.io/tracks/pony

**Comment by SeanTAllen** [comment]
Please note, this is an issue tracker for the Pony tutorial. Exercism is a 3rd party service. It is not officially supported by the Pony project.

**Comment by nazarsh** [comment]
Thanks! Doing a search didn't result in it coming up, and it wasn't listed, hence me filing this. 
![image](https://user-images.githubusercontent.com/8605112/70719594-4a0ebd80-1cc0-11ea-8585-ef3ce24e9e49.png)
Got it on the intent of this issue tracker!

**Comment by SeanTAllen** [comment]
@nazarsh FYI, Your best solution for general questions and getting help is to join the Zulip:

https://ponylang.zulipchat.com/#

There's a beginner help stream for getting started:

https://ponylang.zulipchat.com/#narrow/stream/189985-beginner-help

Most questions you come up with as you work through the tutorial are probably best asked there.

**Comment by nazarsh** [comment]
Thanks so much for the information!
