### ISSUE TITLE
Add `compile_intrinsic` to Keywords

### ISSUE THREAD

**Issue by rhagenson** [ponylang/pony-tutorial#422]
The compile conditional `compile_intrinsic` as mentioned in #216 is not yet in the [Keywords](https://tutorial.ponylang.io/appendices/keywords.html) list.

I am not familiar enough with `compile_intrinsic` to write its definition.

**Comment by SeanTAllen** [comment]
compile_intrinsic means that the implementation is written in C and not available as Pony code.

**Comment by rhagenson** [comment]
Thank you. I will get this added some time in the next couple days between holiday activities.
