### ISSUE TITLE
Statement v. expressions interchanging

### ISSUE THREAD

**Issue by rhagenson** [ponylang/pony-tutorial#440]
I noticed this interchanging while reading [Everything is an expression](https://tutorial.ponylang.io/expressions/control-structures.html#everything-is-an-expression) where the following is said:

> In Pony there are no statements, there are only expressions; everything hands back a value. Your `if` **statement** hands you back a value. Your `for` loop (which we’ll get to a bit later) hands you back a value.

Above emphasis is mine. Certainly this specific instance must be changed, but we make similar expression/statement swaps in the [Keywords](https://tutorial.ponylang.io/appendices/keywords.html), [Use statement](https://tutorial.ponylang.io/packages/use-statement.html), [Match expression](https://tutorial.ponylang.io/pattern-matching/match.html) (where it is later called a "match statement" one before the "Matching on values" section), [Variables](https://tutorial.ponylang.io/expressions/variables.html), and so on. 

It seems there are more instances of "statement" rather than "expression" so before making changes I wanted to open up the conversation on such a sweeping change.

Related point, if `if`, `match`, `for`, variable assignment (asides on [destructive read](https://tutorial.ponylang.io/types/classes.html) talks above this) and so on are expressions, are there instances of Pony statements which will then need to be specifically explained as being unlike the rest of Pony?

**Comment by SeanTAllen** [comment]
Excellent point.
