### ISSUE TITLE
Quality of life improvement: improve navigation on the website

### ISSUE THREAD

**Issue by MonliH** [ponylang/pony-tutorial#457]
This is just a quality of life suggestion for the site, not related to the (well-written!) text. I've found it annoying to go to the next page of the tutorial after reading through the entire page: you have to scroll back to the top then use the navbar on the side.

Two things I can think of to remedy this:
* **Add links for previous and next page** at the bottom of the page. For example, the [next.js documentation](https://nextjs.org/docs/) has this:
  <img width=300 src="https://user-images.githubusercontent.com/30177086/106362204-9287a100-62ef-11eb-9fb4-7e1df82db674.png"></img>
* **Make the navbar "float"** (i.e. `position: sticky`). Again, from the next.js docs there's a floating sidebar:
  <img width=300 src="https://user-images.githubusercontent.com/30177086/106362312-1477ca00-62f0-11eb-9740-fa80fc5d87d3.png"></img>

I'm wondering what people think of this: I'm willing to make a PR by adding this feature. Having both features would also be nice. If we only wanted to implement one, the second one (floating sidebar) is probably easier.

**Comment by SeanTAllen** [comment]
I prefer the first option. I'm not a fan of floating sidebars, I find them very distracting.

**Comment by rhagenson** [comment]
If the sidebars float and still collapse then I am in favor of that, but the first option with previous and next seems to be where the majority is leaning.

**Comment by ergl** [comment]
Now that we have migrated to the new theme which includes a collapsible sidebar and links at the bottom, can this be closed?
