### ISSUE TITLE
causal vs casual

### ISSUE THREAD

**Issue by ohir** [ponylang/pony-tutorial#50]
"Causal" for non native speakers is easily (and unconsciously) mistaken with "Casual".

even docs author fingers got it slipped in
pony-tutorial: docs/runtime/garbage-collection.md [:62:64:]

I'd suggest to either mark <us> in casual with bold or underscore, or warn non natve readers in plain words: docs/types/static-vs-dynamic.md:31: +* All message passing is causal (caUSal not caSUal)".

**Comment by sylvanc** [comment]
Good catch, and good idea. Would you mind filing a PR to both fix it and provide an explanation you think is helpful?
