### ISSUE TITLE
Few notes on generating doc

### ISSUE THREAD

**Issue by steakknife** [ponylang/pony-tutorial#514]
1. Generate doc in ReadTheDoc .md format without creating a binary: `ponyc --docs-public --pass=docs ....` (Note: it documents everything, including built-in types. `--docs-public` only skips doc for private entries.)

2. Install deps to convert them to HTML: `pip3 install mkdocs mkdocs-material`

3a. Either build static HTML docs for hosting on a webserver: `cd {{target}}-docs && mkdocs build` -> `{{target}}-docs/site`

3b. Or serve them locally: `cd {{target}}-docs && mkdocs serve` (existing tutorial step)

**Comment by SeanTAllen** [comment]
This isn't an actionable item. The issues aren't a notepad.
