### ISSUE TITLE
Printable tutorial

### ISSUE THREAD

**Issue by noahemmet** [ponylang/pony-tutorial#6]
(I actually just emailed the same question to the mailing list, but realized this might be a better place.)

Anyway, it'd be great if the tutorial was available as a single-sheet HTML file or PDF, for printing or sending to your favorite read-it-later service. 

Thanks!

**Comment by jkleiser** [comment]
Here is my solution for a single-file markdown or PDF:
https://github.com/jkleiser/pony-onedoc-md

**Comment by jkleiser** [comment]
I have now updated my ‘pony-onedoc-md’ to work with the new mkdocs.yml format introduced in 0.1.6.
I have also made CSS (in src/doc-css.html) that more or less matches the online Pony tutorial.

**Comment by SeanTAllen** [comment]
PDF version is now available at https://www.gitbook.com/book/ponylang/pony-tutorial/details
