### ISSUE TITLE
Generics section needs to be written

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#63]
See: https://groups.io/g/pony+dev/thread/tutorial_is_completely/805994?p=,,,20,0,0,0:RecentPostDate,,,20,2,0,805994

**Comment by aturley** [comment]
I'll help on this.

**Comment by SeanTAllen** [comment]
Thanks @aturley

**Comment by MrMormon** [comment]
Reference capability polymorphism for generics:

https://bluishcoder.co.nz/2016/05/04/bang-hat-and-arrow-in-pony.html

**Comment by doublec** [comment]
Just noting that a generics section was committed recently. Maybe morph this into things that need to be added to it?

**Comment by SeanTAllen** [comment]
Ya. I'm going to close this and it can continue to evolve. Are you planning on writing more @doublec ?

**Comment by doublec** [comment]
Yep, I've got more written but need to mash it into something a little more coherent before doing a pull request.
