### ISSUE TITLE
Code Sharing section needs to be written

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#66]
Content should be on:

'Delegation, default implementations of method bodies in traits and interfaces, using composition instead of inheritance.'

That sort of thing. Contact me if you are interested in taking this on.

**Comment by aturley** [comment]
I'm going to try my hand at writing some delegate documentation.

**Comment by rhagenson** [comment]
@aturley and @SeanTAllen 4+ years later and I am not 100% certain what this Code Sharing section needs to include to consider this issue closed.
