### ISSUE TITLE
Add case functions to the tutorial

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/pony-tutorial#77]

**Comment by aturley** [comment]
I'll take this one.

Note: Currently case methods with guard statements fail to compile due to  [ponylang/ponyc issue 692](https://github.com/ponylang/ponyc/issues/692)

**Comment by aturley** [comment]
Should this go under "Pattern Matching", or be part of "Expressions/Methods", or go somewhere else?

I'm leaning toward making it a separate function under "Pattern Matching". Maybe still have a quick note in "Expressions/Methods" that says, "Case functions are also a thing you should go check them out."

Any thoughts?

**Comment by SeanTAllen** [comment]
They both seem reasonable.

**Comment by jemc** [comment]
@aturley - your "leaning" approach sounds right to me.
