### ISSUE TITLE
with-do blocks catching errors

### ISSUE THREAD

**Issue by jkleiser** [ponylang/pony-tutorial#8]
The docs/expressions/exceptions.md should mention that with-do blocks can catch errors. Are there other constructs other than 'try' that catches errors?

**Comment by georgemarrows** [comment]
@jkleiser does #53 close this for you?
I can't answer your follow-up about other constructs. I haven't seen anything in my few days of poking about though, fwiw.

**Comment by SeanTAllen** [comment]
This is now in the tutorial.
