### ISSUE TITLE
A lot of URL's indexed by search engines currently result in a 404

### ISSUE THREAD

**Issue by hakvroot** [ponylang/pony-tutorial#81]
_Summary_
With the 'doc' path removed from the tutorial a lot of pages indexed by (e.g.) Google point to a "not found" page. From this page it is unfortunately not possible to go to any Pony related page - one can just go to the previous page which is either the originating search page or "about:blank" if the page was opened in a new tab.

_Expected behavior_
When using a search engine to search for information regarding Pony I expect to land on a page containing information.

_Observed behavior_
In most cases after searching for a Pony related subject and clicking on a tutorial.ponylang.org hosted link results in a 404 page with no relevant information or method to go the tutorial. 

_Example_
Indexed URL (404) : `http://tutorial.ponylang.org/docs/capabilities/reference-capabilities.html`.
Actual URL : `http://tutorial.ponylang.org/capabilities/reference-capabilities.html`

_Suggested solution_
If request rewriting is possible at the server level, forward the request (301) to a location with the /docs/ portion dropped. If changing the 404 page is possible, modify it to point a visitor to tutorial.ponylang.org. Through JavaScript it should also be possible to redirect the user automatically from the 404 page if a /docs/ portion is detected in the URL's path (but should not be relied upon).

Hope this helps!

**Comment by rhagenson** [comment]
I am closing this because all my searches just now never 404'ed so it seems to be resolved at this time.
